variable "master_count" {}
variable "node_count" {}
variable "network_name" {}
variable "floating_ip_pool" {}
variable "image_id" {}
variable "image_flavor" {}
variable "security_groups" {}
variable "key_pair" {}
variable "inventory_path" {}
